version: '3.9'

services:
  openproject:
    image: openproject/openproject:latest
    ports:
      - "8888:80"
    environment:
      - OPENPROJECT_SECRET_KEY_BASE=changeme
    volumes:
      - openproject-data:/var/openproject

volumes:
  openproject-data:
