version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspaces
    env_file:
      - dev.env
    volumes:
    - devuser-home:/home/devuser
      - ../workspaces:/workspaces
      - ../.m2:/home/devuser/.m2:rw
      #TODO .m2 is mounted as root 777. we don't like this
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "2222:22"
    extra_hosts:
      - "host.docker.internal:host-gateway"
