version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /root/workspace
    env_file:
      - dev.env
    volumes:
      - root-home:/home/root
      - ../workspace:/root/workspace
      #- ../.m2:/root/.m2:rw
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "2222:22"
    extra_hosts:
      - "host.docker.internal:host-gateway"

#TODO .m2 is mounted as root 777. we don't like this

volumes:
  root-home:
