version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspaces
    env_file:
      - dev.env
    volumes:
      - ../workspaces:/workspaces
      - ../.m2/settings.xml:/home/devuser/.m2/settings.xml:ro
    ports:
      - "2222:22"
    extra_hosts:
      - "host.docker.internal:host-gateway"
